config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: "homes#top"
get '/books' => 'bookers#index'
get '/books/:id' => 'bookers#show',as: 'book'
post '/books' => 'bookers#create'
get '/books/:id/edit' => 'bookers#edit', as: 'edit_book'
patch '/books/:id' => 'bookers#update', as: 'update_book'
delete 'books/:id' => 'bookers#destroy', as: 'destroy_book'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

 validates :title, presence: true
 validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookers_controller.rb
class BookersController < ApplicationController


def index
 @books = Book.all
 @book = Book.new
end

def show
 @book = Book.find(params[:id])
end

def edit
 @book = Book.find(params[:id])

end

def create
 @book = Book.new(book_params)
 if@book.save
 redirect_to book_path(@book.id)
 flash[:notice] = "Book was successfully created."
 else
 @books = Book.all
 render :index
 end
end

def update
 @book = Book.find(params[:id])
 if @book.update(book_params)
 redirect_to book_path(@book.id)
 flash[:notice] = "Book was successfully updated."
 else
 render :edit
 end
end

def destroy
  book = Book.find(params[:id])
  book.destroy
  redirect_to '/books'
end

private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/bookers/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="style.css" />
    <title>Bookers</title>
  </head>


<body>
 <h1>Editing Book</h1>

 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>


　<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

 <div class="field">
  <div>Title</div>
  <%= f.text_field :title %>
  </div>

 <div class="field">
 <div>Body</div>
  <%= f.text_area :body %>
 </div>

 <div class="actions">

  <%= f.submit 'Update Book' %>
 </div>

 <%= link_to "Show", book_path(@book.id) %>
 |
 <%= link_to "Back", "/books" %>

  <% end %>
</body>

app/views/bookers/index.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="style.css" />
    <title>Bookers</title>
  </head>

  <body>
   <h1>Books</h1>

   <table>

    <thead>
     <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
     </tr>
    </thead>

    <tbody>


      <% @books.each do |book| %>
        <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", "/books/#{book.id}" %></td>
        <td><%= link_to "Edit", "/books/#{book.id}/edit" %></td>
        <td><%= link_to "Destroy", "/books/#{book.id}", method: :delete, "data-confirm" => "Are you sure？" %></td>
        </tr>
      <% end %>


    </tbody>

   </table>

   <h2>New book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model:Book.new do |f| %>

  <div class="field">
    <div>Title</div>
  <%= f.text_field :title %>
  </div>

  <div class="field">
  <div>Body</div>
  <%= f.text_area :body %>
  </div>
  <%= f.submit 'Create Book' %>
<% end %>

  </body>

</html>

app/views/bookers/show.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="style.css" />
    <title>Bookers</title>
  </head>

  <body>

　 <p class=success-message>
   <%= flash[:notice] %>
   </p>

   <p>
   <strong>Title:</strong>
   <%= @book.title %>
   </p>

   <p>
   <strong>Body:</strong>
   <%= @book.body %>
   </p>

   <%= link_to "Edit", edit_book_path(@book.id) %>
   |
   <a class="back" href="/books">Back</a>


  </body>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="style.css" />
    <title>Bookers</title>
  </head>

  <body>
   <h1>
     ようこそ
    <strong>Bookers</strong>
     へ！
   </h1>

   <p>
     <strong>Bookers</strong>
     では、さまざまな書籍に関するあなたの意見や
   </p>
   <p>
     印象を共有し交換することができます
   </p>
   <p>
     <a href="/books">start</a>
   </p>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>